### ISSUE TITLE
Display today's event on the map. 

### ISSUE THREAD

**Issue by hmanalai** [Kids-Eat/KidsEat#11]
Currently, the map only shows events that after today (in the future). Change it to today and after today.

**Comment by ovezovs** [comment]
@hmanalai, did we implement this? Do you remember?

**Comment by hmanalai** [comment]
> @hmanalai, did we implement this? Do you remember? I have a feeling that you did implement it but we didn't close the issue

No, we are still showing only future events. I will take it on.
